# Generated by Django 4.2.7 on 2025-08-23 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_detected', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_detections', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='EmotionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_count', models.IntegerField(default=0)),
                ('sad_count', models.IntegerField(default=0)),
                ('angry_count', models.IntegerField(default=0)),
                ('surprised_count', models.IntegerField(default=0)),
                ('fear_count', models.IntegerField(default=0)),
                ('disgust_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stream.person')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], max_length=20)),
                ('confidence', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera_id', models.CharField(default='camera_1', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='stream.person')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
